### ISSUE TITLE
[Bug] [HighwayTools] Lava Source Patching is buggy

### ISSUE THREAD

**Issue by theredstoner** [Avanatiker/client#12]
HighwayTools can get stuck when lava sources are flowing onto the highway. Fix/Improve this feature.

**Comment by EnigmA-008** [comment]
**Ideas**
It works almost all the time fine if the lava soure is one of the blocks that have to be mined (i.e. while extending a 3x3 tunnel to 4x6). the bot scans the blocks to be mined and marks the lava block in purple, netherrack in red. it tries to replace the purple block first. maybe this scan needs to be extended so that the bot scans the blocks that have to be mined and the surrounding blocks, find the lava and fixes it: 
![grafik](https://user-images.githubusercontent.com/76707270/103247108-0687ff80-4966-11eb-9c01-c34d025c7757.png)

The bot tries fix floating lava, maybe it helps to fix the source block with high prio. trying to fix the floating lava may result in more floating lava.
